# Generated by Django 4.2.30 on 2026-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager_feedback',
            field=models.TextField(blank=True, help_text='Manager feedback on the submission.'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('none', 'Not submitted'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Needs revision')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_note',
            field=models.TextField(blank=True, help_text='Member note when submitting the task.'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
