# Generated by Django 4.2.30 on 2026-05-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_manager_feedback_task_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, document, image, etc.).', null=True, upload_to='task_submissions/'),
        ),
    ]
