# Generated by Django 4.2.30 on 2026-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_assignment_file_projectsection_task_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application_question',
            field=models.CharField(blank=True, help_text='Optional suitability question shown to prospective team members.', max_length=300),
        ),
    ]
