# Generated by Django 4.2.30 on 2026-08-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canvas_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='canvas_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
