services:
  - type: web
    name: gfr-platform
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn gfr.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gfr.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_SECRET_KEY
        sync: false
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_BUCKET_NAME
        sync: false
      - key: SUPABASE_REGION
        value: us-east-1
      - key: SUPABASE_MEDIA_URL
        sync: false
