# Generated by Django 4.2.30 on 2026-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text="Fallback icon name (e.g. 'book', 'users', 'calendar', 'lifebuoy'). Used if no image is provided.", max_length=40)),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL. Used if no image is uploaded.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image from your computer. Takes priority over image_url.', null=True, upload_to='landing_features/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landing feature',
                'verbose_name_plural': 'Landing features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
