# Generated by Django 4.2.30 on 2026-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researchinterest_user_biography_user_google_scholar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Postgraduate Student'), ('researcher', 'Researcher'), ('professor', 'Senior Researcher / Professor'), ('assistant_professor', 'Assistant Professor'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('project_manager', 'Project Manager'), ('admin', 'Administrator')], default='student', max_length=32),
        ),
    ]
