# Generated by Django 4.2.30 on 2026-05-05 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional special issue title.', max_length=200)),
            ],
            options={
                'ordering': ['-year', '-volume', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True, help_text='Aims and scope of the journal.')),
                ('issn', models.CharField(blank=True, help_text='e.g. 1234-5678', max_length=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='journal_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['editor', 'admin']}, related_name='edited_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='manuscripts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=24)),
                ('editor_note', models.TextField(blank=True, help_text='Note from the editor to the author.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts', to='journals.issue')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuscripts', to='journals.journal')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManuscriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='manuscript_versions/')),
                ('author_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='journals.manuscript')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.journal'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='invited', max_length=16)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('report', models.TextField(blank=True, help_text='Confidential report to the editor.')),
                ('comments_to_author', models.TextField(blank=True, help_text='Non-anonymous comments for the author.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='journals.manuscript')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('manuscript', 'reviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('journal', 'volume', 'number')},
        ),
    ]
