# Generated by Django 4.2.30 on 2026-05-07 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('task_assigned', 'Task assigned to you'), ('task_submitted', 'Task submitted for review'), ('task_approved', 'Task approved'), ('task_rejected', 'Task needs revision'), ('project_joined', 'Member joined project'), ('project_added', 'Added to project'), ('manuscript_update', 'Manuscript status updated'), ('new_follow', 'New follower'), ('new_message', 'New message')], max_length=24)),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
