# Generated by Django 4.2.30 on 2026-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned to you'), ('task_submitted', 'Task submitted for review'), ('task_approved', 'Task approved'), ('task_rejected', 'Task needs revision'), ('project_joined', 'Member joined project'), ('project_added', 'Added to project'), ('project_application', 'Project application received'), ('project_application_decision', 'Project application decision'), ('manuscript_update', 'Manuscript status updated'), ('new_follow', 'New follower'), ('new_message', 'New message')], max_length=32),
        ),
    ]
