# Generated by Django 4.2.30 on 2026-08-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectinvitation_and_more'),
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_invitation',
            field=models.ForeignKey(blank=True, help_text='Linked when this notification is about a project invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projectinvitation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned to you'), ('task_submitted', 'Task submitted for review'), ('task_approved', 'Task approved'), ('task_rejected', 'Task needs revision'), ('project_joined', 'Member joined project'), ('project_added', 'Added to project'), ('project_application', 'Project application received'), ('project_application_decision', 'Project application decision'), ('project_invitation', 'Project invitation received'), ('project_invitation_declined', 'Project invitation declined'), ('manuscript_update', 'Manuscript status updated'), ('new_follow', 'New follower'), ('new_message', 'New message')], max_length=32),
        ),
    ]
